[project]
name = 'Blockchain-Based-Construction-Project-Management'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.change-order]
path = 'contracts/change-order.clar'
clarity_version = 2
epoch = 2.5

[contracts.contractor-verification]
path = 'contracts/contractor-verification.clar'
clarity_version = 2
epoch = 2.5

[contracts.material-verification]
path = 'contracts/material-verification.clar'
clarity_version = 2
epoch = 2.5

[contracts.milestone-completed]
path = 'contracts/milestone-completed.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
